import type { CSSProperties } from 'react'

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100svh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    boxSizing: 'border-box',
  },
  card: {
    width: '100%',
    maxWidth: 380,
    background: 'var(--bg)',
    border: '1px solid var(--border)',
    borderRadius: 12,
    boxShadow: 'var(--shadow)',
    padding: '40px 32px',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 16,
  },
  title: {
    fontSize: 28,
    margin: 0,
    color: 'var(--text-h)',
  },
  subtitle: {
    margin: 0,
    color: 'var(--text)',
  },
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    width: '100%',
    padding: '12px 20px',
    fontSize: 16,
    fontWeight: 500,
    color: '#fff',
    background: 'var(--accent)',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
  },
  secondaryButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    padding: '10px 20px',
    fontSize: 15,
    fontWeight: 500,
    color: 'var(--text-h)',
    background: 'transparent',
    border: '1px solid var(--border)',
    borderRadius: 8,
    cursor: 'pointer',
  },
  link: {
    color: 'var(--accent)',
    textDecoration: 'none',
    fontWeight: 500,
  },
  spinner: {
    width: 36,
    height: 36,
    borderRadius: '50%',
    border: '3px solid var(--border)',
    borderTopColor: 'var(--accent)',
    animation: 'spin 0.8s linear infinite',
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 14px',
    fontSize: 14,
    fontWeight: 500,
    color: '#16a34a',
    background: 'rgba(22, 163, 74, 0.1)',
    border: '1px solid rgba(22, 163, 74, 0.3)',
    borderRadius: 999,
  },
  errorBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 14px',
    fontSize: 14,
    fontWeight: 500,
    color: '#dc2626',
    background: 'rgba(220, 38, 38, 0.1)',
    border: '1px solid rgba(220, 38, 38, 0.3)',
    borderRadius: 999,
  },
  label: {
    alignSelf: 'flex-start',
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text)',
    margin: 0,
  },
  tokenBox: {
    width: '100%',
    minHeight: 120,
    padding: 12,
    fontFamily: 'var(--mono)',
    fontSize: 12,
    color: 'var(--text-h)',
    background: 'var(--code-bg)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    resize: 'vertical',
    boxSizing: 'border-box',
  },
}
